//! End-to-end example: generate → sign locally with EC P-256 → assemble → revoke
//! against a real Blerify Issuance API environment (default: `demo`).
//!
//! See `README.md` in this directory for setup. In short, drop your
//! service-account JSON, your project's signing private key (PEM), and
//! the matching issuer certificate (PEM) into `config/`, set a few env
//! vars, and run:
//!
//! ```bash
//! cargo run --example end_to_end
//! ```
//!
//! The signing keypair MUST be the one registered for the project on
//! Blerify's side — random keys will fail server validation regardless of
//! whether the cert wraps the matching public key locally.

use std::path::PathBuf;

use anyhow::{Context, Result};
use base64::Engine;
use p256::ecdsa::signature::Signer;
use p256::ecdsa::{Signature, SigningKey};
use p256::pkcs8::DecodePrivateKey;
use p256::SecretKey;

use rust_mdl::{
    AdditionalData, AssembleRequest, BlerifyClient, DrivingCode, DrivingPrivilege, GenerateRequest,
    JwkP256, MdlData, Options, OrganizationUser, RevokeRequest, ServiceAccountCredentials,
    StateChangeMetadata, ValidityInfo,
};

const DEFAULT_BASE_URL: &str = "https://api.demo.blerify.com";
const DEFAULT_CREDS_PATH: &str = "examples/end_to_end/config/credentials.json";
const DEFAULT_SIGNING_KEY_PATH: &str = "examples/end_to_end/config/signing-key.pem";
const DEFAULT_ISSUER_CERT_PATH: &str = "examples/end_to_end/config/issuer-cert.pem";

#[tokio::main]
async fn main() -> Result<()> {
    // Load `examples/end_to_end/.env` if present (created from `.env.example`).
    // Errors are intentionally ignored — env vars set by the shell still win.
    let _ = dotenvy::from_filename("examples/end_to_end/.env");

    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let cfg = Config::from_env()?;

    println!(
        "→ loading service-account credentials from {}",
        cfg.creds_path.display()
    );
    let creds = ServiceAccountCredentials::from_file(&cfg.creds_path)
        .with_context(|| format!("loading {}", cfg.creds_path.display()))?;

    println!(
        "→ loading issuer signing key from {}",
        cfg.signing_key_path.display()
    );
    let signing_key_pem = std::fs::read_to_string(&cfg.signing_key_path)
        .with_context(|| format!("reading {}", cfg.signing_key_path.display()))?;
    let signing_key = parse_signing_key(&signing_key_pem)?;

    println!("→ loading issuer cert from {}", cfg.cert_path.display());
    let issuer_cert = std::fs::read_to_string(&cfg.cert_path)
        .with_context(|| format!("reading {}", cfg.cert_path.display()))?;

    let client = BlerifyClient::new(&cfg.base_url, creds, &cfg.project_id);
    println!(
        "→ client ready: {} (org from credentials, project {})",
        client.base_url(),
        client.project_id(),
    );

    // ---------------------------------------------------------------- 1. generate
    let mut mdl_data = MdlData::new(
        "Doe",
        "John",
        "1987-03-15",
        "2025-10-15",
        "2028-09-30",
        "US",
        "Blerify Demo",
        "8-203-1365",
        // Hex-encoded JPEG bytes. Bundled as a fixture so the example runs
        // out-of-the-box; a real issuer would resize and JPEG-encode the
        // citizen photo per ISO 18013-5 §7.2.2.
        include_str!("fixtures/portrait.hex").trim(),
        vec![DrivingPrivilege {
            vehicle_category_code: "C".into(),
            issue_date: "2025-08-25".into(),
            expiry_date: "2028-09-30".into(),
            codes: vec![DrivingCode { code: "210".into() }],
        }],
        "PA",
    );
    mdl_data.nationality = Some("PA".into());

    let gen_request = GenerateRequest {
        template_id: cfg.template_id.clone(),
        additional_data: AdditionalData {
            mdl_data,
            validity_info: ValidityInfo {
                signed: "2025-10-28T10:10:18Z".into(),
                valid_from: "2025-10-29T20:46:25Z".into(),
                valid_until: "2030-02-13T10:10:18Z".into(),
            },
            // The device public key is normally generated by the wallet and
            // sent to the issuer alongside the claim. Hardcoded here for the
            // example — pubkey only, no security implication.
            device_public_key: JwkP256::ec_p256(
                "iBh5ynojixm_D0wfjADpouGbp6b3Pq6SuFHU3htQhVk",
                "oxS1OAORJ7XNUHNfVFGeM8E0RQVFxWA62fJj-sxW03c",
            ),
            certificate: issuer_cert.clone(),
            kid: cfg.kid.clone(),
            namespaces: vec![],
        },
        organization_user: OrganizationUser {
            id: "8-203-1365".into(),
            did: "did:lac1:1iT5g9gduT4Q5DWE2bnncfnBCnM9uXPWMrCTvhPf2a8wpHWJgFBEZn295t1h9ucnQyvJ"
                .into(),
        },
        options: Options {
            additional_data: true,
            onboard: false,
            update: true,
        },
    };

    println!("\n[1/3] generate — POST /credentials");
    let gen = client
        .generate(&gen_request, None)
        .await
        .context("generate")?;
    println!("       credential id: {}", gen.credential.id);
    println!(
        "       signingMessage length: {} chars",
        gen.signing_message.len()
    );

    // ---------------------------------------------------------------- 2. sign locally
    println!("\n[2/3] sign locally with EC P-256 (ES256)");
    // `signingMessage` is standard base64 (php-mdl uses `base64_decode()` which
    // is standard-alphabet). Some senders return URL-safe base64 instead, so
    // fall back to URL-safe on alphabet mismatch.
    let signing_message_bytes = base64::engine::general_purpose::STANDARD
        .decode(&gen.signing_message)
        .or_else(|_| base64::engine::general_purpose::URL_SAFE_NO_PAD.decode(&gen.signing_message))
        .context("decoding signingMessage as base64 (tried standard then URL-safe)")?;
    let signature: Signature = signing_key.sign(&signing_message_bytes);
    let sig_bytes = signature.to_bytes();
    let signature_hex = hex::encode(sig_bytes);
    debug_assert_eq!(signature_hex.len(), 128);
    println!("       signature: {}…", &signature_hex[..32]);

    // ---------------------------------------------------------------- 3. assemble
    println!("\n[3/3] assemble — PUT /credentials/{{id}}/sign");
    let asm = client
        .assemble(
            &gen.credential.id,
            &AssembleRequest {
                template_id: cfg.template_id.clone(),
                signature: signature_hex,
                kid: cfg.kid.clone(),
                certificate: issuer_cert.clone(),
            },
            None,
        )
        .await
        .context("assemble")?;
    println!("       mdoc length: {} hex chars", asm.mdoc.len());
    println!("       mdoc head:  {}…", &asm.mdoc[..32]);

    // ---------------------------------------------------------------- 4. revoke
    println!("\n[cleanup] revoke — PUT /credentials/{{id}}/revoke");
    client
        .revoke(
            &gen.credential.id,
            &RevokeRequest {
                metadata: StateChangeMetadata {
                    code: "EXAMPLE_CLEANUP".into(),
                    description: "End-to-end example cleanup".into(),
                    category: "test".into(),
                },
            },
            None,
        )
        .await
        .context("revoke")?;
    println!("       revoked.\n");

    println!("✓ end-to-end flow completed against {}", cfg.base_url);
    Ok(())
}

struct Config {
    base_url: String,
    creds_path: PathBuf,
    signing_key_path: PathBuf,
    cert_path: PathBuf,
    project_id: String,
    template_id: String,
    kid: String,
}

impl Config {
    fn from_env() -> Result<Self> {
        Ok(Self {
            base_url: std::env::var("BLERIFY_BASE_URL").unwrap_or_else(|_| DEFAULT_BASE_URL.into()),
            creds_path: env_or_default_path("BLERIFY_CREDS_PATH", DEFAULT_CREDS_PATH),
            signing_key_path: env_or_default_path(
                "BLERIFY_SIGNING_KEY_PATH",
                DEFAULT_SIGNING_KEY_PATH,
            ),
            cert_path: env_or_default_path("BLERIFY_ISSUER_CERT_PATH", DEFAULT_ISSUER_CERT_PATH),
            project_id: required_env("BLERIFY_PROJECT_ID")?,
            template_id: required_env("BLERIFY_TEMPLATE_ID")?,
            kid: required_env("BLERIFY_KID")?,
        })
    }
}

fn env_or_default_path(key: &str, default: &str) -> PathBuf {
    std::env::var(key)
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(default))
}

fn required_env(key: &str) -> Result<String> {
    std::env::var(key).with_context(|| format!("required env var {key} is not set"))
}

/// Parse an EC P-256 private key in either PKCS#8 (`-----BEGIN PRIVATE KEY-----`)
/// or SEC1 (`-----BEGIN EC PRIVATE KEY-----`) PEM format.
fn parse_signing_key(pem: &str) -> Result<SigningKey> {
    let secret = if pem.contains("BEGIN EC PRIVATE KEY") {
        SecretKey::from_sec1_pem(pem)
            .map_err(|e| anyhow::anyhow!("parsing SEC1 EC P-256 private key: {e}"))?
    } else {
        SecretKey::from_pkcs8_pem(pem)
            .map_err(|e| anyhow::anyhow!("parsing PKCS#8 EC P-256 private key: {e}"))?
    };
    Ok(SigningKey::from(secret))
}
